// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FootballTeamManagement_BusinessObject.Models;

public partial class FootballPlayer
{
    public string PlayerId { get; set; }

    public string PlayerName { get; set; }

    public string Achievements { get; set; }

    public DateTime? Birthday { get; set; }

    public string OriginCountry { get; set; }

    public string Award { get; set; }

    public string FootballTeamId { get; set; }

    public virtual FootballTeam FootballTeam { get; set; }
}