// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FootballTeamManagement_BusinessObject.Models;

public partial class Uefaaccount
{
    public int AccountId { get; set; }

    public string AccountPassword { get; set; }

    public string AccountEmail { get; set; }

    public string AccountDescription { get; set; }

    public int? Role { get; set; }
}